FROM nginx:1.21.6-alpine

#ADD config/nginx/default.conf /etc/nginx/conf.d/default.conf
#COPY config/nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www

#ENV TZ=Europe/Moscow
#RUN rm /etc/localtime && mkdir /etc/localtime
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
